import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { FileText, Video, Download } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";
import { toast } from "sonner";

const Notes = () => {
  const { user } = useAuth();
  const [items, setItems] = useState<any[]>([]);

  useEffect(() => {
    if (!user) return;
    (async () => {
      const { data } = await supabase.from("video_artifacts").select("*, videos(*)").eq("user_id", user.id).eq("kind", "notes").order("created_at", { ascending: false });
      setItems(data || []);
    })();
  }, [user]);

  const downloadPdf = (title: string, markdown: string) => {
    const doc = new jsPDF({ unit: "pt", format: "letter" });
    const margin = 50;
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const maxW = pageW - margin * 2;
    let y = margin;

    doc.setFont("helvetica", "bold"); doc.setFontSize(18);
    const titleLines = doc.splitTextToSize(title, maxW);
    doc.text(titleLines, margin, y); y += titleLines.length * 22 + 10;

    doc.setDrawColor(180); doc.line(margin, y, pageW - margin, y); y += 18;
    doc.setFontSize(10); doc.setFont("helvetica", "italic"); doc.setTextColor(120);
    doc.text(`Generated by IntractctVid • ${new Date().toLocaleDateString()}`, margin, y); y += 20;
    doc.setTextColor(0);

    // Strip markdown lightly
    const clean = markdown
      .replace(/^#{1,6}\s+/gm, "")
      .replace(/\*\*(.*?)\*\*/g, "$1")
      .replace(/\*(.*?)\*/g, "$1")
      .replace(/`([^`]+)`/g, "$1")
      .replace(/^\s*[-*]\s+/gm, "• ");

    const blocks = clean.split(/\n\n+/);
    doc.setFont("helvetica", "normal"); doc.setFontSize(11);
    for (const block of blocks) {
      const isHeading = /^[A-Z][^\n]{0,80}$/.test(block.trim()) && block.length < 80;
      doc.setFont("helvetica", isHeading ? "bold" : "normal");
      doc.setFontSize(isHeading ? 13 : 11);
      const lines = doc.splitTextToSize(block.trim(), maxW);
      const lineH = isHeading ? 16 : 14;
      for (const line of lines) {
        if (y + lineH > pageH - margin) { doc.addPage(); y = margin; }
        doc.text(line, margin, y); y += lineH;
      }
      y += 8;
    }

    doc.save(`${title.replace(/[^\w\s-]/g, "").slice(0, 60)}-notes.pdf`);
    toast.success("PDF downloaded");
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div>
        <h1 className="font-display text-3xl font-bold flex items-center gap-3"><FileText className="h-7 w-7 text-primary" /> AI Notes</h1>
        <p className="text-muted-foreground">All AI-generated notes from your videos. Download as PDF anytime.</p>
      </div>
      {items.length === 0 ? (
        <div className="glass-card rounded-xl p-12 text-center text-muted-foreground">
          No notes yet. Open a video and generate notes from the AI panel.
        </div>
      ) : (
        <div className="space-y-4">
          {items.map(it => (
            <details key={it.id} className="glass-card rounded-xl p-5 group" open>
              <summary className="cursor-pointer flex items-center justify-between gap-3 list-none flex-wrap">
                <div className="font-display font-semibold text-lg flex items-center gap-2"><Video className="h-4 w-4 text-primary" /> {it.videos?.title}</div>
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="outline" onClick={(e) => { e.preventDefault(); downloadPdf(it.videos?.title || "Notes", it.content?.notes || ""); }}>
                    <Download className="h-3.5 w-3.5 mr-1.5" /> PDF
                  </Button>
                  <Link to={`/video/${it.video_id}`} className="text-xs text-primary hover:underline">Open video →</Link>
                </div>
              </summary>
              <div className="prose prose-sm prose-invert max-w-none mt-4 prose-headings:text-primary">
                <ReactMarkdown>{it.content?.notes || ""}</ReactMarkdown>
              </div>
            </details>
          ))}
        </div>
      )}
    </div>
  );
};

export default Notes;
